root: true
env:
  browser: true
  es2021: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'prettier'
  - 'plugin:cypress/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: 'module'
plugins:
  - '@typescript-eslint'
rules:
  '@typescript-eslint/no-var-requires': 0
  'no-unused-vars': 'off' # duplicate of @typescript-eslint/no-unused-vars
  'no-debugger': 'off'
  'cypress/no-unnecessary-waiting': 'off'
